# Generated by Django 5.1.4 on 2025-01-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_users_managers_remove_users_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSearchHistory',
        ),
    ]
